title: Muhammad Aji Satrio W
<<<<<<< HEAD
logo: /assets/pict/foto.png
=======
logo: /assets/img/headshot_circle.png
>>>>>>> 48c7761d9d55618b948524d5c37d80ce8ccf9eff
description: Graduated with a degree in electrical engineering, but my passion lies in Data Science. I possess strong analytical abilities and technical skills from my engineering background, which I believe can be valuable in the field of data analysis. Alongside my studies at hacktive8, I have also gained experience with programming languages like Python and SQL, using them to analyze and visualize data sets. I'm eager to apply my knowledge and skills to a rewarding career as a Data Scientist
show_downloads: true
theme: jekyll-theme-minimal