title: Muhammad Aji Satrio W
logo: /assets/pict/foto.png
description: Graduated in electrical engineering, with strong analytical abilities and technical skills. Proficient in Python and SQL for data analysis and visualization. Eager to pursue a rewarding career as a Data Scientist.
#show_downloads: true
theme: jekyll-theme-minimal
